In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../dataset/car_fuel_efficiency_2026.csv")
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [3]:
df = df[["engine_displacement", "horsepower", "vehicle_weight", "model_year", "fuel_efficiency_mpg"]]
df

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
0,2180,243.0,3870,2006,31.9
1,2390,272.0,4210,2008,31.3
2,2320,267.0,4240,1996,27.5
3,2130,258.0,4490,1989,28.5
4,2580,304.0,4510,1994,31.0
...,...,...,...,...,...
9995,2470,271.0,4690,2005,27.4
9996,2300,244.0,4370,1993,30.0
9997,2480,267.0,4590,2014,28.1
9998,2180,270.0,4450,2004,32.2
9999,2380,295.0,4370,2011,30.2

In [4]:
df.isnull().sum()

engine_displacement      0
horsepower             877
vehicle_weight           0
model_year               0
fuel_efficiency_mpg      0
dtype: int64

In [5]:
df.horsepower.describe()

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

# Q3

In [7]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [8]:
def rmse(y, y_pred):
    error = y - y_pred
    se = error ** 2
    mse = se.mean()
    return np.sqrt(mse)

## With 0

In [9]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

np.random.seed(42)
idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]
df_test = df.iloc[idx[n_train + n_val:]]

In [10]:
df_test.horsepower = df_test.horsepower.fillna(0)
df_val.horsepower = df_val.horsepower.fillna(0)
df_train.horsepower = df_train.horsepower.fillna(0)

In [11]:
X_train = df_train[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values
X_train

array([[1900.,  239., 3790., 2015.],
       [2000.,  224., 4380., 1992.],
       [2330.,  286., 4090., 2022.],
       ...,
       [2240.,  255., 4190., 1989.],
       [2430.,  254., 4280., 2020.],
       [2390.,  266., 4220., 1996.]], shape=(6000, 4))

In [12]:
y_train = df_train["fuel_efficiency_mpg"].values
y_train

array([32.5, 29.1, 34.1, ..., 27.7, 31.6, 28. ], shape=(6000,))

In [13]:
w0, w = train_linear_regression(X_train, y_train)

In [14]:
y_pred = w0 + X_train.dot(w)
y_pred

array([34.07471478, 29.24093577, 32.95179055, ..., 29.32203017,
       31.8448482 , 29.69112172], shape=(6000,))

In [15]:
X_val = df_val[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values
X_val

array([[2240.,  265., 3990., 2004.],
       [2390.,  259., 4770., 2019.],
       [2360.,  265., 4320., 2018.],
       ...,
       [2390.,  264., 4550., 2017.],
       [2330.,  244., 4440., 2014.],
       [2170.,  260., 4460., 2021.]], shape=(2000, 4))

In [16]:
y_val = df_val["fuel_efficiency_mpg"].values
y_val

array([30.4, 32.8, 27.8, ..., 30.6, 31. , 30.8], shape=(2000,))

In [17]:
y_pred = w0 + X_val.dot(w)
y_pred

array([31.64502134, 29.86572978, 31.58838899, ..., 30.53133298,
       30.75085098, 31.62912778], shape=(2000,))

In [18]:
rmse_with_0 = round(rmse(y_val, y_pred), 3)
rmse_with_0

np.float64(2.205)

## With mean

In [19]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

np.random.seed(42)
idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]
df_test = df.iloc[idx[n_train + n_val:]]

In [20]:
df_train.horsepower.mean()

np.float64(254.46338337605272)

In [21]:
df_test.horsepower = df_test.horsepower.fillna(df_train.horsepower.mean())
df_val.horsepower = df_val.horsepower.fillna(df_train.horsepower.mean())
df_train.horsepower = df_train.horsepower.fillna(df_train.horsepower.mean())

In [22]:
X_train = df_train[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values
X_train

array([[1900.,  239., 3790., 2015.],
       [2000.,  224., 4380., 1992.],
       [2330.,  286., 4090., 2022.],
       ...,
       [2240.,  255., 4190., 1989.],
       [2430.,  254., 4280., 2020.],
       [2390.,  266., 4220., 1996.]], shape=(6000, 4))

In [23]:
y_train = df_train["fuel_efficiency_mpg"].values
y_train

array([32.5, 29.1, 34.1, ..., 27.7, 31.6, 28. ], shape=(6000,))

In [24]:
w0, w = train_linear_regression(X_train, y_train)

In [25]:
y_pred = w0 + X_train.dot(w)
y_pred

array([33.9590606 , 29.31436861, 32.76131994, ..., 29.30040609,
       31.92376266, 29.67268373], shape=(6000,))

In [26]:
X_val = df_val[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values
X_val

array([[2240.,  265., 3990., 2004.],
       [2390.,  259., 4770., 2019.],
       [2360.,  265., 4320., 2018.],
       ...,
       [2390.,  264., 4550., 2017.],
       [2330.,  244., 4440., 2014.],
       [2170.,  260., 4460., 2021.]], shape=(2000, 4))

In [27]:
y_val = df_val["fuel_efficiency_mpg"].values
y_val

array([30.4, 32.8, 27.8, ..., 30.6, 31. , 30.8], shape=(2000,))

In [28]:
y_pred = w0 + X_val.dot(w)
y_pred

array([31.54288381, 29.92505122, 31.56459523, ..., 30.54408311,
       30.85701236, 31.55313717], shape=(2000,))

In [29]:
rmse_with_mean = round(rmse(y_val, y_pred), 3)
rmse_with_mean

np.float64(2.202)

## Comparison

In [30]:
rmse_with_0

np.float64(2.205)

In [31]:
rmse_with_mean

np.float64(2.202)

# Q4

In [51]:
def train_linear_regression_reg(X, y, r=0.001):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX = XTX + r * np.eye(XTX.shape[0])

    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [52]:
def rmse(y, y_pred):
    error = y - y_pred
    se = error ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [53]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

np.random.seed(42)
idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]
df_test = df.iloc[idx[n_train + n_val:]]

In [54]:
df_test.horsepower = df_test.horsepower.fillna(0)
df_val.horsepower = df_val.horsepower.fillna(0)
df_train.horsepower = df_train.horsepower.fillna(0)

In [55]:
X_train = df_train[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values
X_train

array([[1900.,  239., 3790., 2015.],
       [2000.,  224., 4380., 1992.],
       [2330.,  286., 4090., 2022.],
       ...,
       [2240.,  255., 4190., 1989.],
       [2430.,  254., 4280., 2020.],
       [2390.,  266., 4220., 1996.]], shape=(6000, 4))

In [56]:
y_train = df_train["fuel_efficiency_mpg"].values
y_train

array([32.5, 29.1, 34.1, ..., 27.7, 31.6, 28. ], shape=(6000,))

In [57]:
X_val = df_val[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values
X_val

array([[2240.,  265., 3990., 2004.],
       [2390.,  259., 4770., 2019.],
       [2360.,  265., 4320., 2018.],
       ...,
       [2390.,  264., 4550., 2017.],
       [2330.,  244., 4440., 2014.],
       [2170.,  260., 4460., 2021.]], shape=(2000, 4))

In [58]:
y_val = df_val["fuel_efficiency_mpg"].values
y_val

array([30.4, 32.8, 27.8, ..., 30.6, 31. , 30.8], shape=(2000,))

In [59]:
reg = [0, 0.01, 0.1, 1, 5, 10, 100]

In [60]:
rmse_diff_r = []
for r in reg:
    w0, w = train_linear_regression_reg(X_train, y_train, r)
    y_pred = w0 + X_val.dot(w)
    rmse_diff_r.append(round(rmse(y_val, y_pred), 4))
rmse_diff_r

[np.float64(2.2053),
 np.float64(2.2058),
 np.float64(2.2241),
 np.float64(2.3492),
 np.float64(2.4094),
 np.float64(2.4195),
 np.float64(2.4292)]

# Q5

In [6]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [7]:
def rmse(y, y_pred):
    error = y - y_pred
    se = error ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [8]:
seeds = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
rmse_diff_seed = []
for seed in seeds:
    n = len(df)
    n_val = int(n * 0.2)
    n_test = int(n * 0.2)
    n_train = n - n_val - n_test

    np.random.seed(seed)
    idx = np.arange(n)
    np.random.shuffle(idx)

    df_train = df.iloc[idx[:n_train]]
    df_val = df.iloc[idx[n_train:n_train + n_val]]
    df_test = df.iloc[idx[n_train + n_val:]]

    df_test.horsepower = df_test.horsepower.fillna(0)
    df_val.horsepower = df_val.horsepower.fillna(0)
    df_train.horsepower = df_train.horsepower.fillna(0)

    X_train = df_train[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values

    y_train = df_train["fuel_efficiency_mpg"].values

    w0, w = train_linear_regression(X_train, y_train)

    X_val = df_val[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values
    
    y_val = df_val["fuel_efficiency_mpg"].values

    y_pred = w0 + X_val.dot(w)

    rmse_diff_seed.append(rmse(y_val, y_pred))

rmse_diff_seed

[np.float64(2.239204143046126),
 np.float64(2.2021128210838845),
 np.float64(2.1634197787530947),
 np.float64(2.2043588768539224),
 np.float64(2.2018800943311554),
 np.float64(2.2457851509085134),
 np.float64(2.2697212079524043),
 np.float64(2.190794599933443),
 np.float64(2.216611201686444),
 np.float64(2.2070365928178957)]

In [10]:
round(np.std(rmse_diff_seed), 3)

np.float64(0.029)

# Q6

In [6]:
def train_linear_regression_reg(X, y, r=0.001):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX = XTX + r * np.eye(XTX.shape[0])

    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [7]:
def rmse(y, y_pred):
    error = y - y_pred
    se = error ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [8]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

np.random.seed(9)
idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train + n_val]]
df_test = df.iloc[idx[n_train + n_val:]]

In [9]:
df_test.horsepower = df_test.horsepower.fillna(0)
df_train.horsepower = df_train.horsepower.fillna(0)

In [10]:
X_train = df_train[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values
X_train

array([[2320.,  246., 4100., 2014.],
       [2230.,  252., 4250., 1998.],
       [2700.,  276., 4490., 2008.],
       ...,
       [1800.,  225., 3980., 1994.],
       [1970.,  232., 3560., 2009.],
       [2180.,  254., 3970., 2018.]], shape=(8000, 4))

In [11]:
y_train = df_train["fuel_efficiency_mpg"].values
y_train

array([32.5, 33.2, 32.4, ..., 29.1, 32.2, 35.6], shape=(8000,))

In [12]:
w0, w = train_linear_regression_reg(X_train, y_train, 0.001)

In [13]:
X_test = df_test[["engine_displacement", "horsepower", "vehicle_weight", "model_year"]].values
X_test

array([[2100.,  258., 4060., 2011.],
       [2160.,  223., 4130., 2011.],
       [2190.,    0., 4030., 1975.],
       ...,
       [2240.,  265., 4170., 1982.],
       [2380.,  278., 4210., 1978.],
       [1910.,  220., 3820., 2019.]], shape=(2000, 4))

In [14]:
y_test = df_test["fuel_efficiency_mpg"].values
y_test

array([29. , 35.7, 26.2, ..., 31. , 27.2, 34.3], shape=(2000,))

In [15]:
y_pred = w0 + X_test.dot(w)
y_pred

array([32.28024359, 31.93261369, 28.73827111, ..., 28.70485368,
       27.94324086, 34.32942994], shape=(2000,))

In [16]:
rmse_test = round(rmse(y_test, y_pred), 3)
rmse_test

np.float64(2.236)